version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /company-update
  volumes:
    - .:/company-update:cached
    - ./node_modules:/company-update/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *node
    working_dir: /company-update
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  app:
    <<: *node
    image: danlynn/ember-cli:3.14.0
    working_dir: /company-update/services/app
    entrypoint: ["ember"]
    command: ["serve", "--port", "9905", "--proxy", "http://graphql"]
    tmpfs:
      - /company-update/services/app/tmp
    ports:
      - "9905:9905"
    depends_on:
      - graphql

  graphql:
    <<: *node
    working_dir: /company-update/services/graphql
    entrypoint: ["./node_modules/.bin/gulp"]
    depends_on:
      - mongo
    ports:
      - "9900:80"
    environment:
      <<: *env
      MONGO_DSN: ${MONGO_DSN-mongodb://mongo/cuf}
      GRAPHQL_URI: ${GRAPHQL_URI}
      TENANT_KEY: ${TENANT_KEY}
      PLATFORM_URI: ${PLATFORM_URI}
      PLATFORM_LOGO: ${PLATFORM_LOGO}
      PLATFORM_SECTIONS: ${PLATFORM_SECTIONS}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM: ${SENDGRID_FROM-no-reply@baseplatform.io}
      NOTIFICATION_TO: ${NOTIFICATION_TO}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

  mongo:
    tty: true
    image: mongo:3.4
    volumes:
      - mongo:/data/db
    ports:
      - "9901:27017"

volumes:
  mongo: {}
  yarn-cache: {}
